In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine

df = load_wine()

In [8]:
X = df.data
y = df.target
print(X.shape, y.shape)

(178, 13) (178,)


In [9]:
print(X.min(), X.max())

0.13 1680.0


In [13]:
#minmaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((0, 1))
mmrescaledX = scaler.fit_transform(X)
mmrescaledX

array([[0.84210526, 0.1916996 , 0.57219251, ..., 0.45528455, 0.97069597,
        0.56134094],
       [0.57105263, 0.2055336 , 0.4171123 , ..., 0.46341463, 0.78021978,
        0.55064194],
       [0.56052632, 0.3201581 , 0.70053476, ..., 0.44715447, 0.6959707 ,
        0.64693295],
       ...,
       [0.58947368, 0.69960474, 0.48128342, ..., 0.08943089, 0.10622711,
        0.39728959],
       [0.56315789, 0.36561265, 0.54010695, ..., 0.09756098, 0.12820513,
        0.40085592],
       [0.81578947, 0.66403162, 0.73796791, ..., 0.10569106, 0.12087912,
        0.20114123]])

In [14]:
print(mmrescaledX.min(), mmrescaledX.max())

0.0 1.0


In [15]:
#Standard Scalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
ss_scaled = scaler.fit_transform(X)
ss_scaled

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [16]:
print(ss_scaled.min(), ss_scaled.max())

-3.6791622340370145 4.371372139554767


In [18]:
#Normalizer
from sklearn.preprocessing import Normalizer
norm = Normalizer()
normalizedX = norm.fit_transform(X)
normalizedX

array([[1.32644724e-02, 1.59397384e-03, 2.26512072e-03, ...,
        9.69434383e-04, 3.65402190e-03, 9.92738094e-01],
       [1.25128005e-02, 1.68733218e-03, 2.02859038e-03, ...,
        9.95336401e-04, 3.22299406e-03, 9.95336401e-01],
       [1.10630135e-02, 1.98394467e-03, 2.24454758e-03, ...,
        8.65874158e-04, 2.66487484e-03, 9.96175609e-01],
       ...,
       [1.57227449e-02, 5.07108879e-03, 2.67772446e-03, ...,
        6.99051960e-04, 1.84834078e-03, 9.89336248e-01],
       [1.55136606e-02, 3.05090212e-03, 2.79175213e-03, ...,
        7.06772691e-04, 1.90828627e-03, 9.89481768e-01],
       [2.48340486e-02, 7.20591644e-03, 4.81566123e-03, ...,
        1.07209976e-03, 2.81206495e-03, 9.84222734e-01]])

In [19]:
print(normalizedX.min(), normalizedX.max())

0.00014484038599355936 0.9978349045602742


In [20]:
#binarizer
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.5)
binaryX = binarizer.fit_transform(X)
binaryX

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [21]:
#Scaling
from sklearn.preprocessing import scale
data_standardized = scale(X)
data_standardized.mean(axis=0)

array([ 7.84141790e-15,  2.44498554e-16, -4.05917497e-15, -7.11041712e-17,
       -2.49488320e-17, -1.95536471e-16,  9.44313292e-16, -4.17892936e-16,
       -1.54059038e-15, -4.12903170e-16,  1.39838203e-15,  2.12688793e-15,
       -6.98567296e-17])

In [22]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
data = np.array(['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot'])
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)
integer_encoded

array([0, 0, 2, 0, 1, 1, 1, 2, 0, 2, 1], dtype=int64)

In [23]:
#One Hot Encoding
ohe_encoder = OneHotEncoder(sparse_output=False) # renamed sparse-> sparse_output in v1.2
vals_encoded = data.reshape(len(data),1)
ohe_encoded = ohe_encoder.fit_transform(vals_encoded)
print(ohe_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [24]:
inverted = ohe_encoder.inverse_transform(ohe_encoded)
inverted

array([['cold'],
       ['cold'],
       ['warm'],
       ['cold'],
       ['hot'],
       ['hot'],
       ['hot'],
       ['warm'],
       ['cold'],
       ['warm'],
       ['hot']], dtype='<U4')