In [2]:
!pip install keras

     ---------------------------------------- 1.7/1.7 MB 1.5 MB/s eta 0:00:00


In [4]:
! pip install tensorflow

     -------------------------------------- 272.8/272.8 MB 1.4 MB/s eta 0:00:00
     -------------------------------------- 440.7/440.7 kB 1.5 MB/s eta 0:00:00
     ---------------------------------------- 4.1/4.1 MB 904.8 kB/s eta 0:00:00
     ---------------------------------------- 1.3/1.3 MB 1.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
     ---------------------------------------- 24.4/24.4 MB 2.7 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 2.4 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 1.5 MB/s eta 0:00:00
     -------------------------------------- 126.5/126.5 kB 1.9 MB/s eta 0:00:00
     -----------------------------

In [26]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from sklearn.metrics import confusion_matrix
from keras.utils import to_categorical

In [27]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [28]:
# One-hot encode the target variable
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y.reshape(-1, 1))

C:\Users\ganes\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [29]:
# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [30]:
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [31]:
# Compile the model
model.compile(optimizer=SGD(lr=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

C:\Users\ganes\anaconda3\lib\site-packages\keras\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [32]:
# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=0)

In [33]:
# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1/1 [==============================] - 0s 181ms/step - loss: 0.4731 - accuracy: 0.7000
Test Loss: 0.47311073541641235
Test Accuracy: 0.699999988079071


In [34]:
y_pred = to_categorical(model.predict(X_test))

1/1 [==============================] - 0s 64ms/step


In [35]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Convert multilabel-indicator to integer labels
label_encoder = LabelEncoder()
y_test_encoded = label_encoder.fit_transform(np.argmax(y_test, axis=1))
y_pred_encoded = np.argmax(y_pred, axis=1)

# Calculate confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_encoded, y_pred_encoded)
print(cm)

[[10  0  0]
 [ 9  0  0]
 [11  0  0]]
